### ISSUE TITLE
"No JSON object could be decoded" when trying to create / list alerts

### ISSUE THREAD

**Issue by VinGit67** [9b/google-alerts#23] opened 2019-07-14 07:25 UTC
**Bug Description**
When I try to create an alert or list alerts from the commandline , I get the error "No JSON object could be decoded" with the following traceback:

**$ google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime'**
Traceback (most recent call last):
  File "/usr/bin/google-alerts", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/google_alerts/cli/manage.py", line 148, in main
    ga.authenticate()
  File "/usr/lib/python2.7/site-packages/google_alerts/__init__.py", line 279, in authenticate
    valid = self._session_check()
  File "/usr/lib/python2.7/site-packages/google_alerts/__init__.py", line 186, in _session_check
    self._process_state()
  File "/usr/lib/python2.7/site-packages/google_alerts/__init__.py", line 226, in _process_state
    state = json.loads(i.text[15:-1])
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
 
Had no problems with the installation and seeding:

**$ google-alerts seed --driver ~/Downloads/chromedriver --timeout 60**
[*] Filled in email address and submitted.
[*] Filled in password and submitted.
[!] Waiting for the authentication cookie or 60 seconds
[$] Session has been seeded, google-alerts is ready for use.

**To Reproduce**
1. exec: google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime'

**Expected behavior**
Creation of Alert

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RHEL 7.6
 - Browser Chrome
 - Version 74

**Additional context**

**Comment by 9b** [comment] 2019-07-14 13:58
This is a duplicate of #21.

**Closed by 9b** 2019-07-14 13:58 UTC
Labels: duplicate
